name: peptide-prediction
channels:
  - conda-forge
  - pytorch
  - bioconda
dependencies:
  - python=3.9
  - numpy>=1.23.5
  - pandas>=1.5.3
  - scikit-learn>=1.3.0
  - pytorch>=1.12.0
  - matplotlib>=3.5.3
  - seaborn>=0.12.2
  - jupyter
  - biopython>=1.79
  - scipy>=1.9.0
  - statsmodels>=0.13.0
  - pip
  - pip:
    - fair-esm>=2.0.0
